export let clubAllowedCollegeYears = [
  { club_id: 1, college_year: "1" },
  { club_id: 2, college_year: "3" },
  { club_id: 2, college_year: "4" },
  { club_id: 2, college_year: "5" },
  { club_id: 3, college_year: "Бүх курс" },
  { club_id: 4, college_year: "Бүх курс" },
  { club_id: 5, college_year: "1" },
  { club_id: 5, college_year: "2" },
  { club_id: 5, college_year: "3" },
  { club_id: 6, college_year: "3" },
  { club_id: 6, college_year: "4" },
  { club_id: 6, college_year: "5" },
  { club_id: 7, college_year: "Бүх курс" },
  { club_id: 8, college_year: "Бүх курс" },
  { club_id: 9, college_year: "3" },
  { club_id: 9, college_year: "4" },
  { club_id: 10, college_year: "2" },
  { club_id: 10, college_year: "3" },
  { club_id: 10, college_year: "4" },
  { club_id: 11, college_year: "Бүх курс" },
  { club_id: 12, college_year: "Бүх курс" },
  { club_id: 13, college_year: "1" }
];
